version = 0.1

[default.deploy.parameters]
stack_name = "google-zoho-sync"
resolve_s3 = true
s3_prefix = "google-zoho-sync"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
