AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GoogleCalendarZoho Lambda triggered every hour

Globals:
  Function:
    Timeout: 60
    Runtime: java17
    MemorySize: 512

Resources:
  GoogleZohoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.LambdaHandler::handleRequest
      CodeUri: .
      Runtime: java17
      Architectures:
        - x86_64
      Role: arn:aws:iam::721152523618:role/lambda-execution-role-google-zoho
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 10-5 ? * * *)
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: live

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:PutParameter
              Resource: arn:aws:ssm:us-east-1:721152523618:parameter/prod/calendar-zoho/credentials

      Environment:
        Variables:
          OFFICE_ADDRESS: "1333 S Fenbrook Ln, Bloomington, IN 47401"
          DYNAMODB_TABLE_NAME: "ProcessedGoogleCalendarEvents_ZohoIntegration"
          REGION: "us-east-1"
          DYNAMODB_TTL: "30"  # 1 hour in days
          LOG_LEVEL: "DEBUG"
          PARAM_NAME: "/prod/calendar-zoho/credentials"

